-- Safe accommodation import for the event-area hotel candidates.
-- Adds only rows whose title is not already present. It does not delete or update existing listings.
-- Prices are market-reference FROM prices, not confirmed room rates.

insert into public.listings
  (title, type, city, city_id, price, rating, review_count, images, amenities, max_guests, bedrooms, description, nearest_stadium, distance_to_stadium, available)
select * from (values
  ('Hampton Inn Baltimore-Downtown-Convention Center', 'hotel', 'Baltimore', 'baltimore', 117, 0, 0, ARRAY['/images/hotel-luxury.jpg','/images/hotel-room.jpg']::text[], ARRAY['WiFi','Front desk','Breakfast','Parking']::text[], 2, 1, 'Event-stay candidate near M&T Bank Stadium. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'M&T Bank Stadium', '0.8 miles', true),
  ('Hilton Baltimore Inner Harbor', 'hotel', 'Baltimore', 'baltimore', 175, 0, 0, ARRAY['/images/hotel-room.jpg','/images/hotel-luxury.jpg']::text[], ARRAY['WiFi','Pool','Gym','Connecting rooms']::text[], 4, 2, 'Inner Harbor hotel candidate for M&T Bank Stadium event trips. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'M&T Bank Stadium', '0.9 miles', true),
  ('Canopy by Hilton Baltimore Harbor Point', 'hotel', 'Baltimore', 'baltimore', 200, 0, 0, ARRAY['/images/city.jpg','/images/hotel-luxury.jpg']::text[], ARRAY['WiFi','Harbor views','Gym','Restaurant']::text[], 2, 1, 'Premium Baltimore stay candidate for event travellers. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'M&T Bank Stadium', '1.4 miles', true),
  ('Hampton Inn & Suites Dallas-Arlington North', 'hotel', 'Arlington', 'dallas', 91, 0, 0, ARRAY['/images/hotel-room.jpg','/images/city.jpg']::text[], ARRAY['WiFi','Breakfast','Parking','Indoor pool']::text[], 4, 2, 'Group-friendly Arlington event-stay candidate near AT&T Stadium. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'AT&T Stadium', '1.7 miles', true),
  ('Homewood Suites Dallas-Arlington', 'hotel', 'Arlington', 'dallas', 103, 0, 0, ARRAY['/images/apartment-2.jpg','/images/hotel-room.jpg']::text[], ARRAY['WiFi','Breakfast','Kitchenette','Pool']::text[], 4, 2, 'Suite-style Arlington candidate for families and event groups. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'AT&T Stadium', '1.8 miles', true),
  ('Loews Arlington Hotel', 'hotel', 'Arlington', 'dallas', 289, 0, 0, ARRAY['/images/hotel-luxury.jpg','/images/city.jpg']::text[], ARRAY['WiFi','Pool','Spa','Concierge']::text[], 2, 1, 'Premium Arlington event-stay candidate. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'AT&T Stadium', '0.6 miles', true),
  ('Hilton Chicago', 'hotel', 'Chicago', 'chicago', 250, 0, 0, ARRAY['/images/hotel-luxury.jpg','/images/city.jpg']::text[], ARRAY['WiFi','Gym','Pool','Restaurant']::text[], 2, 1, 'Downtown Chicago candidate for Soldier Field event weekends. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'Soldier Field', '1.3 miles', true),
  ('Homewood Suites Chicago Downtown South Loop', 'hotel', 'Chicago', 'chicago', 169, 0, 0, ARRAY['/images/apartment-2.jpg','/images/hotel-room.jpg']::text[], ARRAY['WiFi','Kitchenette','Breakfast','Connecting rooms']::text[], 4, 2, 'Practical suite option for groups attending Soldier Field events. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'Soldier Field', '1.0 mile', true),
  ('The Anthem Los Angeles Stadium District', 'hotel', 'Inglewood', 'la', 131, 0, 0, ARRAY['/images/hotel-luxury.jpg','/images/city.jpg']::text[], ARRAY['WiFi','Pool','Airport access','Gym']::text[], 2, 1, 'Stadium-district hotel candidate for major SoFi events. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'SoFi Stadium', '0.6 miles', true),
  ('Hilton Garden Inn LAX/El Segundo', 'hotel', 'Inglewood', 'la', 134, 0, 0, ARRAY['/images/hotel-room.jpg','/images/city.jpg']::text[], ARRAY['WiFi','Pool','Airport access','Gym']::text[], 2, 1, 'Practical airport-area hotel candidate for SoFi Stadium visitors. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'SoFi Stadium', '3.5 miles', true),
  ('Homewood Suites by Hilton Los Angeles International Airport', 'hotel', 'Inglewood', 'la', 162, 0, 0, ARRAY['/images/apartment.jpg','/images/hotel-room.jpg']::text[], ARRAY['WiFi','Breakfast','Kitchenette','Pool']::text[], 4, 2, 'Suite-style option for families and groups travelling to SoFi Stadium. Representative room image and market-reference from price; final room type, price, and availability are confirmed before payment.', 'SoFi Stadium', '3.1 miles', true)
) as new_listing(title, type, city, city_id, price, rating, review_count, images, amenities, max_guests, bedrooms, description, nearest_stadium, distance_to_stadium, available)
where not exists (
  select 1 from public.listings existing where lower(existing.title) = lower(new_listing.title)
);
